### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by srg-kostyrko** [srg-kostyrko/obsidian-journal#10]
Add Calendar view similar to Calendar community plugin (as it will be easier to customize it this way).

**Comment by srg-kostyrko** [comment]
Released in 1.1.0

**Comment by Cito** [comment]
Nice, thanks. Quick feedback:

- What are the "pick date" and "today" buttons good for? They don't seem to do anything except moving the calendar month. But you can do that already with the "<>" buttons.
- Would be good to show interval journal entries in reverse order, since the last ones are usually more interesting.
- The Obsidian calendar plugin also shows whether daily notes exist and how long they are. I found that feature very useful. Maybe we can add that as well.
- Maybe start (and end?) dates of interval based journal entries could be also somehow marked in the calendar view.
- Maybe the current interval could be particularly highlighted (similarly to today's date).
- The "show weeks" option doesn't seem to work.

**Comment by srg-kostyrko** [comment]
Thank you for feedback

> What are the "pick date" and "today" buttons good for? They don't seem to do anything except moving the calendar month. But you can do that already with the "<>" buttons.

Yeh they currently move to corresponding month (current one for today and the month around picked date)
Pick date main reason is to quickly navigate back in past (as you can click on month name to select monthn 2 clicks, and clicking year after that will allow to change year quickly)
I think I'll change both to also open corresponding daily note. 

> Would be good to show interval journal entries in reverse order, since the last ones are usually more interesting.

chronological order seemed logical, but you are right reverse order might be interesting. I'll make this configureable

> The Obsidian calendar plugin also shows whether daily notes exist and how long they are. I found that feature very useful. Maybe we can add that as well.

It already shows that there is note (given note is connected to a journal - reindexing old notes is high on my priorities list).
As for length - will think about that.

> Maybe start (and end?) dates of interval based journal entries could be also somehow marked in the calendar view.

I'll add this as part of configurable highlights https://github.com/srg-kostyrko/obsidian-journal/issues/18

> Maybe the current interval could be particularly highlighted (similarly to today's date).

Good point, will add that

> The "show weeks" option doesn't seem to work.

Weeks are shown only if you have journal with weekly notes enabled. Apparently might be confusing as it is now. I'll change that "Show weeks" setting to also have "Don't show" option and so that is does not depend on weekly notes enabled
