### ISSUE TITLE
Calendar view: add setting to show interval based journal entries in reverse order

### ISSUE THREAD

**Issue by srg-kostyrko** [srg-kostyrko/obsidian-journal#20]

**Comment by srg-kostyrko** [comment]
Released in 1.2.0

**Comment by Cito** [comment]
I made the request for this feature because I thought that all (existing) intervals would be shown. But just noticed that the calendar actually shows only the intervals for the current month (but also the non-existing ones). Therefore showing the intervals in reverse order makes less sense, but still good to have it configurable.
