### ISSUE TITLE
Journals breaks {{time}} in templates

### ISSUE THREAD

**Issue by CasparStanley** [srg-kostyrko/obsidian-journal#77]
**'Journals' overrides the core 'Templates' plugin's `{{date}}` and `{{time}}` properties, breaking `{{time}}` entirely.** 

The behavior in Templates is that `{{date}}` and `{{time}}` is the current moment. With Journals it perhaps makes sense that the `{{start_date}}`/`{{date}}` property is set to midnight, so `{{date:HH:mm}}` shows 00:00. 

But `{{time}}` does not work, and there seems to be no easy way to retrieve the current time — for labeling the time of creating the note for example — without other community plugins such as 'Templater', which should not be necessary.

Would it be possible to bring back a `{{time}}` or a `{{current_time}}`?

> Not sure if this is intended, an edge case, or whatever. I seem to only be able to find solutions where people use 'Templater' and I am perfectly set up with just the core plugin and integrating Journals has been awesome but a little unfortunate that I can't log my time of creating my daily (and now weekly) notes automatically anymore.

**Comment by srg-kostyrko** [comment]
This is not intended - I just missed this variable.
I'll add it within couple days

**Comment by CasparStanley** [comment]
Thank you so much! Incredible work on the plugin overall, and I'm excited to see the 2.0 version!

**Comment by srg-kostyrko** [comment]
fixed in 1.4.3

I added support for `{{time}}` and `{{title}}` (that I missed as well.
Also for more clarity there is now also `{{current_date}}` `{{current_time}}`
Default format is fixed for now (will change this in v2) but you can override it as with other variables
Please note that for your use case of note creation date you should use `{{current_date}}` instead of `{{date}}` (as fate is alias to {{start_date}} and might be not current date
